# Generated by Django 4.0.3 on 2022-03-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email_address',
            field=models.EmailField(max_length=30),
        ),
    ]
